---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ddnsclient.fullname" . }}
  labels:
    {{- include "ddnsclient.labels" . | nindent 4 }}
rules:
  {{- $roleYaml := .Files.Get "files/rbac/role.yaml" | fromYaml -}}
  {{- $rules := $roleYaml.rules -}}
  {{- toYaml $rules | nindent 2 -}}
