{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ddnsclient.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddnsclient.labels" . | nindent 4 }}
{{- end }}
